### ISSUE TITLE
Duplicate DNSLink TXT record

### ISSUE THREAD

**Issue by lidel** [ipfs/distributions#1053]
ipfs ls /ipns/dist.ipfs.tech/kubo/v0.24.0-rc2 is flaky because we have two dnslink TXT records for some reason:

```console
$ dig +short TXT _dnslink.dist.ipfs.tech @1.1.1.1
"dnslink=/ipfs/QmTdbtbfzGrgoFbbeAM3N9kdWWJtUNmm4rGSQGPycnHYYt"
"dnslink=/ipfs/QmegzKtEkh5ST7TWDCRsEwVmBoHhbuQyTuKtHkjVxXWtXj"
```

DNS spec does not define order of records, and they are returned in random order.  
If we are unlucky, we get old one which does not have the RC2, and ipfs ls returns with exit code 1 and error:
```
Error: no link named "v0.24.0-rc2" under QmZaCQbvsxerzwknjEURf5HQ6ftNsRz6AWAFTut7br6exf
```

Could be some race condition in  [dnslink-dnsimple](https://www.npmjs.com/package/dnslink-dnsimple) tool [this Github Action](https://github.com/ipfs/distributions/blob/fb6f1c158467aad46cbd72f53d662ba1802111dd/.github/workflows/main.yml#L148-L153) use for updating DNSLink at DNSimple, or a bug in DNSSimple  (our DNS host) itself.

**Comment by lidel** [comment]
I've removed duplicate DNS TXT records (for both .io and .tech), and the issue is resolved. 

I'm assuming a hiccup on the dnsimple end, but if we have this problem again, we need to investigate  the https://www.npmjs.com/package/dnslink-dnsimple angle, maybe API changed, and we need to update that tool.

**Comment by hacdias** [comment]
It's happening again, I have no permissions to remove it.

**Comment by cewood** [comment]
Seems related to API changes that DNSimple seems to have made a some point, and we discovered as part of https://github.com/protocol/bifrost-infra/issues/2814 and https://github.com/ipfs-shipyard/dnslink-dnsimple/pull/21

**Comment by hacdias** [comment]
We'll need to also update https://github.com/ipfs-shipyard/js-dnslink-dnsimple then

**Comment by lidel** [comment]
Asked @olizilla to give me and @hacdias  publishing rights to the [NPM package](https://www.npmjs.com/package/dnslink-dnsimple), but switching to deterministic GO version may be more stable, given how finnicky JS is.

I'll open a PR later today.
