### ISSUE TITLE
No gobuilder

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/distributions#13]
Trying to get this running it fails for me as I do not have gobuilder setup, and I'm not sure how to go about that. Can we get rid of that as there is already a todo in the code?

```
bin/gobuilder-cli: bin
	#TODO: make this not require a go compiler...
	go get github.com/Luzifer/gobuilder/cmd/gobuilder-cli
	cp $(gbcli) bin/gobuilder-cli
```

cc @jbenet @whyrusleeping

**Comment by whyrusleeping** [comment]
what is the output that this fails with?

**Comment by Luzifer** [comment]
If no `gobuilder-cli` is available on the system `$(gbcli)` will be empty and the `cp` will fail. The variable is filled way before the `go get`.

**Comment by Dignifiedquire** [comment]
als @Luzifer said, `cp bin/gobuilder-cli` fails and prints usage instructions for `cp` :laughing:

**Comment by jbenet** [comment]
> Can we get rid of that as there is already a todo in the code?

we can't get rid of it-- we need it to install the other needed tools. for now, get it by running 
```
go get -u github.com/Luzifer/gobuilder/cmd/gobuilder-cli
# afterwards, this should work:
make bin/gobuilder-cli
```

---

We could use `ipget` to install gobuilder-cli or even everything else.

@Luzifer would you be willing to run an ipfs node with gobuilder and add the bins to ipfs + expose the links? we could then pin our own things, save you bandwidth, and people can download with `ipget` which auto-verifies checksums.

**Comment by jbenet** [comment]
@Dignifiedquire if you don't have go, you can download it from here: https://gobuilder.me/github.com/Luzifer/gobuilder/cmd/gobuilder-cli

@Luzifer maybe make a shell-based install for `gobuilder-cli`?

**Comment by jbenet** [comment]
![](http://www.mouthmag.com/issues/58/graphics/bootstraps.gif)

**Comment by Dignifiedquire** [comment]
I figured out what the problem was.. I put all my `PATH` config into `.zshrc` and it turns out if I run `make` it does not know about those even though it's executed from `zsh`. So even though everything was installed it didn't find it :( But I got it working now by copying the  go path configs into `.bash_profile`

**Comment by Dignifiedquire** [comment]
Closing in favor of #16
