### ISSUE TITLE
urls broken on ipfs-sees-all

### ISSUE THREAD

**Issue by daviddias** [ipfs/distributions#147]
reported by @reit-c on https://github.com/ipfs/website/issues/180

**Comment by asymmetric** [comment]
I would like to add that the urls for `gx` and `gx-go` are broken as well.

**Comment by diasdavid** [comment]
@whyrusleeping @lgierth could you check?

**Comment by lgierth** [comment]
What's broken are the links to github (docs, changelog, issues, repo), they're starting with `https://github.com//ipfs-see-all/`

**Comment by whyrusleeping** [comment]
its probably that the author isnt set in the dist.json files

**Comment by jessicaschilling** [comment]
Other than the fact that v1.0 doesn't contain a changelog - which is noted in #228 - these are remedied. Closing.
