### ISSUE TITLE
Downloads blocked by Chrome

### ISSUE THREAD

**Issue by montanaflynn** [ipfs/distributions#149]
I was trying to download https://dist.ipfs.io/#ipget but chrome blocked it:

<img width="336" alt="screen shot 2017-09-11 at 11 53 46 am" src="https://user-images.githubusercontent.com/24260/30291488-fce7f5a4-96e7-11e7-980a-5584201bda48.png">
 
The only explaination was a link to https://support.google.com/chrome/answer/6261569?visit_id=1-636407527663057153-1807376163&p=ib_download_blocked&hl=en&rd=1

**Comment by diasdavid** [comment]
Also, how out of date is `ipget`? Has it been updated with every single IPFS release? Is it part of the release process?

**Comment by Kubuxu** [comment]
ipget is quite out of date, I think I have resurrected its code few releases before but currently it doesn't work very well as far as I know.

It needs some more work and better release process (release with go-ipfs).

**Comment by montanaflynn** [comment]
This is not limited to ipget, any of the downloads on https://dist.ipfs.io are blocked by chrome.

**Comment by lgierth** [comment]
This should be resolved sometime soon today -- we already got a positive validation response from Google Webmaster Tools.

**Comment by lgierth** [comment]
Can confirm this is still an issue

**Comment by montanaflynn** [comment]
I think this has since been fixed, at least with Chrome Version 61.0.3163.91 (Official Build) (64-bit)
