### ISSUE TITLE
asciinema for go-ipfs

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributions#17]
we need one. here's a super basic one i made: https://asciinema.org/a/ev9so7mlfqme0254s50oqiw1l but it's so off.

i want to cover:
- `ipfs init`
- `ipfs cat` the welcome readme
- `ipfs add -r .` a big directory of files
- `ipfs cat` files just added
- `ipfs ls` dirs just added
- `ipfs add` a big file (progress bar)

maybe we could cover:
- changing a file, adding dir again, noting some same, some different hashes
- statrting ipfs daemon
- `ipfs swarm peers`
- `ipfs cat` through the network -- a file i didnt have.

what else? other ideas?

**Comment by Mossfeldt** [comment]
https://asciinema.org/a/104105
No idea if this is still needed but it was easy so I made this quick one.

**Comment by jessicaschilling** [comment]
Closing since we're addressing terminal tips/animations in IPFS docs as a while, but feel free to re-open an issue in https://github.com/ipfs/docs if desired. Thanks!
