### ISSUE TITLE
Add arm64 builds

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/distributions#175]
The arm64 is quite popular right now so I think it warrants its own build.

**Comment by magik6k** [comment]
Would fix https://github.com/ipfs/go-ipfs/issues/4583 too

**Comment by renich** [comment]
Any progress on this one?

**Comment by Stebalien** [comment]
@renich arm64 now builds but we have yet to start building it by default. Assuming we merge https://github.com/ipfs/distributions/pull/182, we should have support by the next release.

**Comment by renich** [comment]
Cool! Thanks!
