### ISSUE TITLE
Windows builds missing

### ISSUE THREAD

**Issue by djdv** [ipfs/distributions#186]
Current master of `go-ipfs` can't be built on Windows because `gx` is missing.
https://github.com/ipfs/go-ipfs/pull/5009 points to /ipfs/QmXtsjCX29kcdeSjrijWiFTK1qwQNW8UrEWDi8okuC2Pog which has bad builds:
https://ipfs.io/ipfs/QmXtsjCX29kcdeSjrijWiFTK1qwQNW8UrEWDi8okuC2Pog/gx/v0.13.0/build-log-windows-amd64

We should add a validation method that assures binaries were built successfully and/or exist.

**Comment by Stebalien** [comment]
Hm. Looks like gx failed to correctly install go-ipfs-cmdkit.

**Comment by Stebalien** [comment]
This has been fixed.
