### ISSUE TITLE
Provide builds for OpenBSD

### ISSUE THREAD

**Issue by teratorn** [ipfs/distributions#195]
Would it be possible to provide builds for openbsd?

**Comment by djdv** [comment]
While it should be possible, I'm not sure the process of adding platforms to the official distribution pipeline.
It is less of a technical matter and more of a logistical one, as the builds have to be maintained, stored, and served.

Randomly pinging @Stebalien
Do we have any requirements or process for adding platforms?
Should we instead try to cooperate with 3rd party maintainers? In this case, OpenBSD package maintainers. I know @kyledrake was interested in this as well.

**Comment by Stebalien** [comment]
It looks like the current issue is that go-ipfs doesn't build on openbsd due to our fuse library. I've filed a bug: https://github.com/ipfs/go-ipfs/issues/5334.

**Comment by teratorn** [comment]
This FUSE, right? https://github.com/billziss-gh/cgofuse  -  https://man.openbsd.org/fuse.4
Maybe it's just the Go support? I'm no expert on FUSE, however.

**Comment by djdv** [comment]
@teratorn 
That implementation is the one I am targeting for the next version of mount. [repo](https://github.com/djdv/go-ipfs/tree/feat/win-mount)
The current version uses https://github.com/bazil/fuse

**Comment by vext01** [comment]
Hi,

OpenBSD is a moving target that provides no backward compat at all. Generally it's better to have binaries built via the ports tree. I've already imported go-ipfs into the ports tree, although we are little behind.

**Comment by Stebalien** [comment]
Fixed in #299 (with no fuse support).
