### ISSUE TITLE
domain?

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributions#20]
What should the url / domain be for this site?

could be:

- update.ipfs.io
- distributions.ipfs.io
- dist.ipfs.io
- releases.ipfs.io
- downloads.ipfs.io
- ipfs.io/downloads
- ipfs.io/dl
- ipfs.io/releases
- ipfs.io/dist
- ipfs.io/distributions

**Comment by jbenet** [comment]
Right now a release is at update.ipfs.io -- but i think it is not just a page for updating, it's a page for finding + installing new things, so i'm more inclined toward the `distributions` or `releases` variety

**Comment by jbenet** [comment]
cc @lgierth @whyrusleeping

**Comment by Dignifiedquire** [comment]
I think dist.ipfs.io is the best

**Comment by whyrusleeping** [comment]
I used update for the ipfs-update stuff so i wouldnt interfere with any dist.ipfs.io work that people were doing. It can be changed to whatever you guys like

**Comment by RichardLitt** [comment]
dist.ipfs.io. :)

**Comment by lgierth** [comment]
yeah dist.ipfs.io is fine -- no SSL for that yet but I'll get a wildcard cert soon (ipfs/infrastructure#138)

**Comment by Dignifiedquire** [comment]
@lgierth why not use https://letsencrypt.org they don't support wildcard but single ones are free

**Comment by lgierth** [comment]
Because I don't wanna have to do that dance every time we setup a new subdomain :)

**Comment by jbenet** [comment]
yeah agreed. let's just pay the mafia their protection tax.

**Comment by jbenet** [comment]
(which is quickly becoming their annoyance/farmville tax, yay! \o/)

**Comment by Dignifiedquire** [comment]
@lgierth did you get the domain yet? If that is all sorted please close this issue :)

**Comment by Dignifiedquire** [comment]
http://dist.ipfs.io/ is now a thing!
