### ISSUE TITLE
ipfs-update v1.5.3 is missing from the (https://|ipns/)dist.ipfs.io/#ipfs-update

### ISSUE THREAD

**Issue by axelsimon** [ipfs/distributions#201]
Hi there, title says it all: v1.5.3 isn't listed on the site.

Upside is when you are running v1.5.3 and see that v1.5.2 is supposedly the latest, you can feel like you are already in the future!

Thanks :slightly_smiling_face:

**Comment by Stebalien** [comment]
1.5.3 hasn't been released, you probably built from source.

(I should have made that 1.5.3-dev)

**Comment by Stebalien** [comment]
I've appended -dev to the current release version to avoid this confusion.
