### ISSUE TITLE
Binary distribution for IPFS-cluster arm64?

### ISSUE THREAD

**Issue by ItalyPaleAle** [ipfs/distributions#225]
I noticed that there’s currently no arm64 (Linux) binary distribution for ipfs-cluster (CLI and daemon). Is there a reason for that?

I have managed to compile it myself and it’s been running fine. But manual compilation on arm64 can be a bit painful and it would be great to have pre-compiled binaries!

**Comment by gedw99** [comment]
I also would love to have a ARM binary.
Using RaspPI

**Comment by hsanjuan** [comment]
Thanks for the heads up, I have added arm64 now to the build matrix. Unfortunately, there is no pretty way to build the last version without rebuilding all the other architectures so arm64 will only be present next time a release comes out.

**Comment by ItalyPaleAle** [comment]
@hsanjuan Thank you!
