### ISSUE TITLE
Final copy for 1.0

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/distributions#23]
This is the copy that needs to be written/reviewed:

### Descriptions

- [ ] ipfs-update
- [ ] go-ipfs (review)
- [ ] fs-repo-migrations

### Changelogs

These are linked, but we need to make sure they actually exist (link is: `<repo>/CHANGELOG.md`)

- [ ] ipfs-update
- [ ] go-ipfs
- [ ] fs-repo-migrations

**Comment by RichardLitt** [comment]
@Dignifiedquire I'm a bit confused what you're asking from us in this issue.

**Comment by RichardLitt** [comment]
I wasn't sure where to find the taglines or the changelog to edit, but I edited the descriptions.

**Comment by Dignifiedquire** [comment]
Taglines are no more

**Comment by jbenet** [comment]
i think we should keep taglines-- even if we dont display them in the page. we may want a big index listing of all the dists with one-line space. (so (big page: name + desc) or (index: name + tagline)

**Comment by Dignifiedquire** [comment]
@jbenet we never really had them, that's why I dropped them for now. If you write some I'm happy to include them

**Comment by jbenet** [comment]
a start:
- go-ipfs: IPFS node and toolchain (in Go).  (or: IPFS service and toolchain (in Go))
- fs-repo-migrations: IPFS filesystem repo version migration tool.
- ipfs-update: IPFS update tool and version manager.
- ipget: wget for IPFS: retrieve files over IPFS and save them locally.
- station: IPFS Node Desktop App  (or something better)
