### ISSUE TITLE
Dist page references "Darwin" instead of "MacOS" or "OS X"

### ISSUE THREAD

**Issue by momack2** [ipfs/distributions#235]
// Bug reported by @tmcw
![Screen Shot 2019-04-19 at 3 34 59 PM](https://user-images.githubusercontent.com/618519/56446663-cdeee200-62b8-11e9-9529-adbc1cf6c304.png)
Right now - the dist page lists a "darwin" binary instead of OS X or MacOS - which may confuse some users. I think this may be coming from the mkdist.js file, but I'm not sure where that's being called from. Looks like @dignifiedquire was the last person to touch this thoroughly and might have ideas? Happy to submit a PR if someone can give me the high-level sense of where all I need to make changes. =]

**Comment by dignifiedquire** [comment]
Historically many projects have called OS X and macOS "Darwin" on their download page which is why we used Darwin here. I believe moving forward switching to macOS (as it is the official name now from Apple), will make much more sense to most users.

**Comment by momack2** [comment]
Note that we currently use "OS X" in the subtext under the "Download go-ipfs" button - it'd be great to change that too to be consistent!

**Comment by Stebalien** [comment]
It looks like we _tried_ to fix this at one point but failed... I can't figure out how to access `$.Site.Params` from an amber template and the documentation for using amber with hugo is non-existent (and the error messages are useless).

**Comment by dignifiedquire** [comment]
I can take a look at it next week.

**Comment by jessicaschilling** [comment]
Hi, @dignifiedquire @Stebalien @momack2 ...
This recently came up in https://github.com/ipfs/website/issues/339 as well. I can address the inconsistencies in ipfs.io and docs.ipfs.io, but I'm hitting a wall with the distro page. May I please request one of you take a look? Thank you!

**Comment by Stebalien** [comment]
I've taken a look, it's just a bit of a pain to fix (I kept running into issues with hugo).
