### ISSUE TITLE
user testing feedback

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributions#24]
@Dignifiedquire this is looking great -- took it out for a spin with people.

some feedback:

- i ran this by 6 people. 3 were hackers. 1 other had coded something at some point. 2 were non technical.
- they all generally liked the page ("looks {good, ok, fine, functional} to me")
- they all were fine navigating
- they all were fine with the columns + clicking.
- in iOS safari it rendered weird, the columns didnt go away after click, and the anchor was a bit offset.
- 2 had trouble noticing that "docs / changelog / all versions" was clickable. 
- it is not very clear that blue text is links in this page. it's a different color and the glow isn't very noticeable in some screens. an underline on hover would be good. 
- 4 had trouble knowing where to download. didnt know the platform grid was links-- (1 thought it was just a listing of what it worked with). "Ok, how do i download it?" was a common question.
- 3 people suggested ["a (big) (green) button with a down arrow"](https://ipfs.io/ipfs/QmZ5hMju6mEAD8LyoBtP5ZFGbio3mjSE5zhqDbUvhuajnu/cap.png).
- might be ok to add "Downloads:" as a title above the grid (i dont like how it looks, but it makes it clear. -- or "Choose platform to download:")
- but what will be very good is to have smart button that detects user's OS and downloads that platform. fine to delay till later if much trouble.
- people were distracted by much text-- fixed when i made the min-size of each distribution "page" (`.d-component { min-height: 700px }` -- about a screen-height's worth. when we add the asciinema or jpgs and so on it will get there, but may be good to just do it (even it blank) to make sure the user is focused on one release at a time even if there is no media.
- (surprising to me) people were mostly fine once in the "all versions" part. -- crude dir listing was ok. they got to the zip! but they did snag on the platforms listing 
- 2 people were looking for osx and did not know "what the hell is darwin?" so we should consider renaming from Go's to more common OS name

![](https://ipfs.io/ipfs/QmPodAjcN6HuT41Q1ZFyEwpz2rdkHEz7kc6rCRiWMQbNaw/cap.png)
![](https://ipfs.io/ipfs/QmNbLfzJhYmNZCF6VyTTV4mJTKfp4yUVgM8BF3gscMkjvs/cap.png)

i can do more user testing if useful.

**Comment by jbenet** [comment]
oh:
- 2 people wanted to go to ipfs homepage from here. they tried clicking "ipfs" in the top left. or wanted more links in the top bar, or "as the first entry in the navigation"

**Comment by Dignifiedquire** [comment]
where do you see darwin? it already says Mac OS X? or do you mean the binary?

**Comment by Dignifiedquire** [comment]
Thanks @jbenet for the thorough testing. I will try to improve on this later this week.

**Comment by whyrusleeping** [comment]
I think the mapping from `darwin` to `osx` should be done in the UI. most of the time i download binaries for osx, the actual file i get has darwin in its name

**Comment by jbenet** [comment]
@whyrusleeping they ran into a snag in the directory listing (`darwin_amd64`).

> most of the time i download binaries for osx, the actual file i get has darwin in its name

I feel that too, however most end users do not. 

we could solve this by symlinking `osx_amd64 -> darwin_amd64`

**Comment by Dignifiedquire** [comment]
Most of these are resolved now. Let's open up individual issues for things that come up again.
