### ISSUE TITLE
Add RSS feed of new releases to dist.ipfs.io

### ISSUE THREAD

**Issue by olizilla** [ipfs/distributions#241]
## This issue has a bounty!
Successfully closing this issue by making a PR of production-ready code can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## How to claim this bounty
Want to work on this bounty project? Please leave a comment on this issue, and we'll be back in touch ASAP to discuss specifics.

## The need in brief
It'd be great to get an RSS feed for our releases. We have one on the GitHub releases page https://github.com/ipfs/go-ipfs/releases.atom but as dist.ipfs.io is our canonical reference, it would be better to offer a feed ourselves.

## The approach
Design:
1. Read in all `dist.json` files.
2. Sort by date.
3. Take the latest N (20?) releases.
4. Generate an atom feed, linked from the main dist page.

Language:
We can either do this in a shell script (run from the `site` target) or we can write a JavaScript program and manage it with NPM (probably easier to get an atom feed this way).

**Comment by Stebalien** [comment]
Design:

1. Read in all `dist.json` files.
2. Sort by date.
3. Take the latest N (20?) releases.
4. Generate an atom feed, linked from the main dist page.

Language:

We can either do this in a shell script (run from the `site` target) or we can write a JavaScript program and manage it with NPM (probably easier to get an atom feed this way).

**Comment by jay-dee7** [comment]
hey @olizilla, can i get to work on this issue over the weekend?

**Comment by hsanjuan** [comment]
@jay-dee7 go ahead

**Comment by jessicaschilling** [comment]
Hi @jay-dee7 - just checking in on this one? Thanks!

**Comment by jay-dee7** [comment]
hey @jessicaschilling i've been flooded with work recently. I'll try my best to share an update this weekend

**Comment by jay-dee7** [comment]
@jessicaschilling @olizilla just want to make sure that i'm thinking of the right away to approach this since i'm having a hard time understanding exactly what `read in file dist.json` means here.

I'm wondering i should collect all the releases from the github repos of ipfs' projects. then bundle them inside a json file with project name as the key, and then make the rss feed out of it (like an aggregated rss feeds from multiple repositories)

**Comment by jessicaschilling** [comment]
@Stebalien -- I believe the approach came from your [note](https://github.com/ipfs/distributions/issues/241#issuecomment-517021669), are you able to advise @jay-dee7?

Please note that Olizilla is AFK for a few months, so let's not disturb him here. Thanks!

**Comment by Stebalien** [comment]
`make` builds a `releases` directory with a `dist.json` file per release (`releases/*/*/dist.json`). However, I'm not actually sure if that's the _best_ approach. It's probably better to just include the _latest_ release of each dist.

1. For each dist in `dists`.
2. Read `dists/$thing/current` to get the latest version.
3. Look at the filesystem timestamp on `dist/$thing/current` to get the build date (should be good enough).
4. Create an RSS entry for this release.

That way, users can subscribe to the RSS feed to get the all the latest releases.

**Comment by neatonk** [comment]
This issue is on the Bounty Board under [Open Bounties](https://github.com/ipfs/devgrants/projects/1#column-7126098), but it looks like it has been assigned. If this bounty is available, I would like to work on it. If not, no worries.

**Comment by jessicaschilling** [comment]
@jay-dee7 -- do you intend to work through this one? **Please let us know by the end of Thursday, 9 July** - else we'll re-assign it. Thank you!

**Comment by jay-dee7** [comment]
sure @jessicaschilling please reassign this to @neatonk. with my current situation, i dont think if i can work on this even this weekend.

**Comment by jessicaschilling** [comment]
@neatonk -- all yours. One note: Before implementing how this fits into the site visually, please check in with a quick concept sketch. Thank you!

**Comment by neatonk** [comment]
Will do. Thanks!

**Comment by neatonk** [comment]
I've looked into this briefly and I think the best approach would be to use the RSS template provided by Hugo. I'll copy the default template from [here](https://github.com/gohugoio/hugo/blob/v0.74.3/tpl/tplimpl/embedded/templates/_default/rss.xml) and modify it to enumerate `$.Site.Data.releases` instead of `$pages` on [line 28](https://github.com/gohugoio/hugo/blob/v0.74.3/tpl/tplimpl/embedded/templates/_default/rss.xml#L28). A nearly empty feed is already being generated by Hugo and this will cause it to be populated with the list of current releases.

**Comment by jessicaschilling** [comment]
@Stebalien, does this sound like a reasonable approach to you? Thanks!

**Comment by neatonk** [comment]
Regarding the visual aspect of this, I think we could include the same "Available as RSS" link and icon as is used on the [IPFS blog](https://blog.ipfs.io/), above or below the "About" section of the distributions page. Alternatively, this could be included in the footer, the header, or the nav. I would prefer to add the icon/link to the top of the about section as on the blog. It will be easy to discover here, will match the blog, and will not complicate the layout at smaller display widths.

Here is a quick mockup for reference...
![Screen Shot 2020-08-05 at 17 16 33](https://user-images.githubusercontent.com/21178/89465285-d97d4b00-d73f-11ea-9625-80a2b0d5a972.png)

**Comment by jessicaschilling** [comment]
@neatonk Mockup is great -- the only thing I would suggest is bringing the text size of "Available as RSS" down a small amount so it doesn't interrupt the hierarchy between the headline and the body copy. What about making the same size as the text in the left nav, but not boldface like the left nav is?

**Comment by Stebalien** [comment]
> @Stebalien, does this sound like a reasonable approach to you? Thanks!

Definitely. I didn't realize hugo indexed those.

**Comment by jessicaschilling** [comment]
Closed by #312, thanks @neatonk!
