### ISSUE TITLE
Can't Download: ipfs-update_v1.5.2_linux-arm

### ISSUE THREAD

**Issue by ilyaigpetrov** [ipfs/distributions#246]
```sh-session
wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-arm.tar.gz
--2019-06-23 18:40:39--  https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-arm.tar.gz
Resolving dist.ipfs.io (dist.ipfs.io)... 209.94.90.1, 2602:fea2:2::1
Connecting to dist.ipfs.io (dist.ipfs.io)|209.94.90.1|:443... connected.
HTTP request sent, awaiting response...
```
And then it hangs. Browser can't download it too. Also tried several days ago with the same result.

My location: Russia (we have censorship but this ip [is not](https://reestr.rublacklist.net/search/?q=209.94.90.1) in the list).

**Comment by djdv** [comment]
That's unfortunate.
I don't have access to a machine in Russia but from my current location (Barcelona, Spain) and my home (Pennsylvania, USA) I'm able to retrieve this. 
![Screenshot 2019-06-25 at 09 07 45](https://user-images.githubusercontent.com/13862850/60076879-f536b500-9728-11e9-87c0-52eb4cffe69a.png)

So there may be a temporary network issue. I'm not sure the censorship status.

**Comment by ilyaigpetrov** [comment]
I still can't download it, it lasts for several days already. Provider is RosTeleCom.
Sometimes I mange to get 17% (512,00K) but then it halts.

**Comment by ilyaigpetrov** [comment]
Also check other links too:
```sh-session
wget https://dist.ipfs.io/go-ipfs/v0.4.21/go-ipfs_v0.4.21_freebsd-amd64.tar.gz
--2019-06-25 20:18:45--  https://dist.ipfs.io/go-ipfs/v0.4.21/go-ipfs_v0.4.21_freebsd-amd64.tar.gz
Resolving dist.ipfs.io (dist.ipfs.io)... 209.94.90.1, 2602:fea2:2::1
Connecting to dist.ipfs.io (dist.ipfs.io)|209.94.90.1|:443... connected.
HTTP request sent, awaiting response... 
```

**Comment by ilyaigpetrov** [comment]
13 Fail 8 Ok:
https://r.h-t.co/en/1/e2dab682-7a98-e911-80bd-0003ff7328cc

**Comment by Stebalien** [comment]
We have been having some issues with our gateway that we are currently working on fixing. That could be causing this.

**Comment by jessicaschilling** [comment]
Closing (stale), but please re-open if issues persist. Thank you!
