### ISSUE TITLE
Architecture matrix is ugly

### ISSUE THREAD

**Issue by Stebalien** [ipfs/distributions#254]
Like, absolutely horrible!
![2019-08-12-221444_1186x400_scrot](https://user-images.githubusercontent.com/310393/62916758-9c5dc300-bd4e-11e9-9b30-f3d1729b701c.png)

**Comment by jessicaschilling** [comment]
I can see what's happening here, but not sure how to fix it:
- There's a table with `colspan` of 6, and that's being divided by the number of `arch`s that exist
- Unfortunately, that means we get rows with varying numbers of `arch` values, and thus uneven `colspan` values for cells
- Solution probably needs to allocate a cell per row for each possible `arch` and leave it blank if no `arch` exists for that row

I'm assuming this would be a very easy fix for someone ... else. Anyone want to take a stab?

**Comment by jessicaschilling** [comment]
Somewhat related: https://github.com/ipfs/distributions/pull/289 for changes to visual branding in general. It's probably worth looking at that to avoid any conflicts (though that PR doesn't touch the tables).

**Comment by jessicaschilling** [comment]
Amended: Making some changes in #289 that should close this issue, at least in a non-embarrassing way.
