### ISSUE TITLE
go-ipfs 0.4.22 not runnable on darwin amd64

### ISSUE THREAD

**Issue by olizilla** [ipfs/distributions#258]
From a fresh download of the latest go-ipfs v0.4.22 for darwin amd64 via https://dist.ipfs.io/go-ipfs/v0.4.22/go-ipfs_v0.4.22_darwin-amd64.tar.gz

I get

```console
$ ./go-ipfs/ipfs version
-bash: ./go-ipfs/ipfs: cannot execute binary file
```

<details>

```console
$ wget https://dist.ipfs.io/go-ipfs/v0.4.22/go-ipfs_v0.4.22_darwin-amd64.tar.gz
--2019-08-13 13:03:19--  https://dist.ipfs.io/go-ipfs/v0.4.22/go-ipfs_v0.4.22_darwin-amd64.tar.gz
Resolving dist.ipfs.io (dist.ipfs.io)... 209.94.90.1
Connecting to dist.ipfs.io (dist.ipfs.io)|209.94.90.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20900005 (20M) [application/gzip]
Saving to: ‘go-ipfs_v0.4.22_darwin-amd64.tar.gz’

go-ipfs_v0.4.22_dar 100%[===================>]  19.93M  4.40MB/s    in 4.6s    

2019-08-13 13:03:24 (4.37 MB/s) - ‘go-ipfs_v0.4.22_darwin-amd64.tar.gz’ saved [20900005/20900005]

$ tar -xzvf go-ipfs_v0.4.22_darwin-amd64.tar.gz 
x go-ipfs/install.sh
x go-ipfs/ipfs
x go-ipfs/LICENSE
x go-ipfs/README.md

$ ./go-ipfs/ipfs version
-bash: ./go-ipfs/ipfs: cannot execute binary file
```

</details>

The same steps for v.0.4.21 work.

**Comment by olizilla** [comment]
From @djdv:

> Related the Windows binary's have no postfix (.exe)
> and it's an ELF

**Comment by djdv** [comment]
Same for the Darwin binaries.
`ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=72ce9e3b62f5a73c3efac40a5e4af3008ba5aac0, for GNU/Linux 3.2.0, not stripped`

(how do apostrophes work. I think I meant to say "the binary's postfix is missing" 😂)
