### ISSUE TITLE
rendering issue on chromium 47

### ISSUE THREAD

**Issue by noffle** [ipfs/distributions#28]
Using this url: http://v04x.ipfs.io/ipfs/QmUCqDJ2dVkdfiMrkgsM7PYNVL91GY8LdvpitxKL71biRp/

Running Chromium 47.0.2526.106 on 64-bit Linux. All text is invisible:

![invisible](http://v04x.ipfs.io/ipfs/QmSSCwDnvC7NwnPfR7BpowpBQooKE5FjDmkAaExenPkVrz/blank.png)

Firefox renders this fine, however. I haven't dug into this any deeper, but am happy to try if you aren't able to reproduce. :)

**Comment by Dignifiedquire** [comment]
@noffle can you please try with the new version: http://v04x.ipfs.io/ipfs/QmeMofwoHniP576g1VhLZmGBK6MtN83XYuqGkBQU3VZVb1

**Comment by noffle** [comment]
Seems to work -- can no longer repro.

**Comment by Dignifiedquire** [comment]
great
