### ISSUE TITLE
make index pages/cards

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributions#3]
- generate per-dist index card (card.html)
- make the global index page (`cat dists/*/card.html >>index.html`)

inspired by iojs

**Comment by jbenet** [comment]
card: 

![](http://gateway.ipfs.io/ipfs/QmXyevWX86x7y3uYSWfuJAKmxyPspVycjKd1YH81QCC9ee/cap.png)

**Comment by jbenet** [comment]
progress example: 

![](http://gateway.ipfs.io/ipfs/QmabFreCqiNndo7kU8K9wa3LkWez2p1iLvbdRSiQmpMZdf/cap.png)

**Comment by Dignifiedquire** [comment]
Resolved in  #11
