### ISSUE TITLE
Drop support for macOS 32-bit binaries.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/distributions#311]
The last macOS products not able to run 64-bit applications (thus only running 32-bit applications) are the 2011 Mac mini. As referenced in #273, Apple requires all binaries to be notarized before a user can run them. Having to manually sort out Apple notarization for a binary that very few (if any) people are going to use is a waste of energy. We should drop support for macOS 32-bit binaries. Removing support for the 32-bit macOS binary also cleans up the releases page of Go-IPFS a tiny bit.

Users who want/need to run IPFS on a 32-bit macOS system can still build an executable themselves. We can provide support to those who need it if anyone ever does.

**Comment by jessicaschilling** [comment]
@lidel, I think you're aware of this discussion already, but name-dropping you in case you're not. 😊

**Comment by lidel** [comment]
iiuc removing [this line](https://github.com/ipfs/go-ipfs/blob/73419b934bc7ad196997c0263af3de01716b1681/mk/util.mk#L20) from go-ipfs build pipeline should do the trick for future releases 
(cc @Stebalien @aschmahmann who may be more familiar)

Open question: should we remove old 32bit releases?

**Comment by johnnymatthews** [comment]
I'd leave the old releases there on the off chance that anyone needs them. We should throw a mini blog post together to explain why we're dropping support for macOS 32-bit binaries. I don't mind writing that. The major reasons for dropping the support are:

- Apple stopped releasing 32-bit devices back in 2011.
- Removing this simplifies our build process, kinda.
- Makes the releases page _slightly_ tidier and easier to navigate.

Any other reasons why dropping macOS 32-bit support is a good thing?

**Comment by aschmahmann** [comment]
@lidel that looks right to me, but my familiarity with our build scripts is currently pretty low so @Stebalien should probably confirm there's nowhere else that needs changing.

**Comment by Stebalien** [comment]
> Any other reasons why dropping macOS 32-bit support is a good thing?

IIRC, the _only_ reason is simplifying code signing on macos, right? Dropping support doesn't actually simplify any part of our build process.

Note: I'd _rather_ just get proper code signing support.

---

To drop support, we'd just remove the `darwin 386` line from the `dists/go-ipfs/build_matrix` file in this repo. The "supported platforms" line in the go-ipfs repo is just for tests (and we might as well continue testing).

**Comment by johnnymatthews** [comment]
> the only reason is simplifying code signing on macos

Yeah pretty much, everything else is just a bonus I guess.

>  I'd rather just get proper code signing support.

By that do you mean you'd rather keep the 32-bit version around, and just get the signing done properly? For what it's worth, [I have no strong feelings one way or the other](https://www.youtube.com/watch?v=ussCHoQttyQ), but it seems kinda fruitless to build and host something that doesn't get used. Saying that, I have no access to metrics, so I don't know if the 32-bit version gets used or not.

**Comment by Stebalien** [comment]
> By that do you mean you'd rather keep the 32-bit version around, and just get the signing done properly?

Yes.

Building and hosting it is pretty much free. I mean, we host builds for openbsd on arm. Basically, my point is that building/hosting one one more platform isn't an issue for us. The only real issue here is code signing.

**Comment by lidel** [comment]
Ack, signing/notarization is tracked in https://github.com/ipfs/distributions/issues/273

**Comment by johnnymatthews** [comment]
Cool beans. Can close this issue then.
