### ISSUE TITLE
Go downloads hierarchy is broken

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributions#33]
The version listings for the go packages got screwed up, they now have a _directory_ for a version with just a `go-ipfs.zip` inside. This is broken, please restore the old schema, which is typical of traditional systems, and which tools already depend on:

- `go-ipfs_$version_$platform.$archive` -- eg `go-ipfs_v0.3.11_amd-64.tar.gz` - this way it is clear on a downloads folder what version you just downloaded, and it does not replace older versions.
- `.zip` is fine for windows, but please use `.tar.gz` for unix platforms, as some zip tools ignore/lose permissions. since we will ship binaries and shell scripts it is important that they _absolutely always_ keep permissions.

To be clear, we want: 

```
.
├── go-ipfs
│   ├── latest -> v0.3.7
│   ├── v0.3.6
│   │   ├── go-ipfs_v0.3.6_darwin-386.tar.gz
│   │   ├── go-ipfs_v0.3.6_darwin-amd64.tar.gz
│   │   ├── go-ipfs_v0.3.6_linux-386.tar.gz
│   │   ├── go-ipfs_v0.3.6_linux-amd64.tar.gz
```

**Comment by jbenet** [comment]
this is important before formally shipping it in a blog post, or writing tools for it

**Comment by jbenet** [comment]
Please respect design constraints as speced out in https://github.com/ipfs/distributions#how-this-repo-works

**Comment by dignifiedquire** [comment]
This is fixed in the latest version
