### ISSUE TITLE
When publishing distribution `bootstrap.js` may change

### ISSUE THREAD

**Issue by gammazero** [ipfs/distributions#336]
When publishing a distribution (`make publish`), it was observed that there was a small difference in `bootstrap.js` between the one previously published and the newly published one.  The comments say that the version of `bootstrap.js` is the same.

Need to investigate whether this is something that happens as a result of building on different platforms or if this can happen some other way.

This did not cause any problem but may cause otherwise identical distributions to appear different.

**Comment by lidel** [comment]
@gammazero do you remember OS and versions? Please reopen if still relevant and you are able to attach CIDs of impacted files.
