### ISSUE TITLE
Dealing with glibc linking and CGO

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/distributions#348]
glibc v2.32 seems to have breaking changes compared to prior versions of glibc. This means that if the binaries are built with glibc >= 2.32 they will not be compatible with prior versions. For example, building on stock Ubuntu 20.10 will result in the build not running on Ubuntu 20.04.

The main options seem to be:
1. Disable CGO
  - not an option for all binaries (e.g. go-ipfs requires them for plugins)
 2. Statically link glibc (and all associated C libraries)
   - IIUC just linking glibc itself can cause a number of problems due to their still being some reliance on the system's glibc
   - static linking all the C dependencies won't work for plugins
3.  Build in an environment where older glibc is supported (e.g. glibc = 2.31 as in Ubuntu 20.04)

Note: while go-ipfs could drop support for external plugins we might still run into issues if we want to include other C libraries such as databases, WASM VMs, etc.

For now the easiest thing to do is to is option 3 by spinning up a VM. However, having a standardized build environment seems like a reasonable thing anyway perhaps we should go back (I heard it may have been this way a number of years ago) to building inside of docker containers.

Update: We should also run some script in this repo like https://gist.github.com/fasterthanlime/17e002a8f5e0f189861c to verify that the glibc versions used are below whatever our support threshold is.

cc @mvdan @hsanjuan @gammazero

**Comment by mvdan** [comment]
Docker containers is what I would do; one could start with images like golang:1.16.2-buster, since that's Debian stable and includes glibc 2.28. A container for Go builds is unnecessary for pure Go builds, but if we want cgo, one needs some way to pin the versions of C libraries.

>  IIUC just linking glibc itself can cause a number of problems due to their still being some reliance on the system's glibc

For static linking of C libraries, I'd consider musl instead, which is actually designed with static linking in mind. It also works well with Go, since it's libc-compatible (but not glibc-compatible).

> static linking all the C dependencies won't work for plugins

I'd be interested to hear more - I'd imagine this should work.

**Comment by aschmahmann** [comment]
> I'd be interested to hear more - I'd imagine this should work.

How? If the plugins are in-tree then CGO isn't required, and if the plugins are out-of-tree then you don't have them available at compile time to perform the static linking.

**Comment by mvdan** [comment]
Perhaps I misunderstood. By static linking I mean to cgo libraries, like libc. Go plugins are never statically linked, as that would defeat their purpose - they'd just become normal Go packages.

**Comment by aschmahmann** [comment]
Closed by #352
