### ISSUE TITLE
Produce easier to digest diff of updates

### ISSUE THREAD

**Issue by aschmahmann** [ipfs/distributions#357]
Currently the README indicates that when doing an update we should use `ipfs object diff` to compare the current and proposed versions of the website. Unfortunately, `ipfs object diff` mostly shows the files that changed but doesn't make it easy to see exactly what's changed. It'd be nice if we could get the diff to be easier to digest (inspiration coming from https://github.com/ipfs/http-api-docs/pull/41).

The commands I tend to use are:
`ipfs object diff <old> <new>`
`ipfs get <oldCID>/path/to/file -o=oldFile`
`ipfs get <newCID>/path/to/file> -o=newFile`
`git diff <oldFile> <newFile>`

It's also helpful to recall that `ipfs` commands can be called with `--enc=json` to get JSON encoded output that should be easier to parse.

While this is likely most useful after dist updates are being built in CI having the basics will already save some time. Additionally, while the `ipfs object diff` command is deprecated and we'd like to build something better we don't have to do that quite yet to make something useful 😄.

**Comment by aschmahmann** [comment]
cc @guseggert

**Comment by guseggert** [comment]
Picking this up
