### ISSUE TITLE
Should we update DNSLink on merge to master?

### ISSUE THREAD

**Issue by lidel** [ipfs/distributions#372]
Current workflow assumes DNSLink will be updated manually by filling a PR against [this `yml` in protocol/infra](https://github.com/protocol/infra/blob/master/dns/config/dist.ipfs.io.yaml) (private PL repo). 

We could automate the process and update DNSLink every time `master` branch is updated, 
or have a separate `production` branch if we want to have an additional step for pushing changes to production.

The question: do we want to do this, or is the requirement  for manual PR against private repo a security feature?

cc @aschmahmann @Stebalien @hsanjuan @olizilla @BigLep for any thoughts

**Comment by Stebalien** [comment]
A PR against master makes sense, but we'll want to double check to lock down who can do that. That's how our websites update as well.

**Comment by lidel** [comment]
We had a quick chat about this and the safer design is to automate the  PR against  `protocol/infra` as a safety feature.

### Proposed design

Tweak  `main.yml` workflow when it builds new commit pushed to the master branch (eg. after a PR merge):

1. At the end of `master` build, check if CID changed (compare to current `/ipns/dist.ipfs.io`)
2. If changed,  open PR at  `protocol/infra`  titled "Update DNSLink at dist.ipfs.io" with link to the commit/github action.

Note: this requires token that has PR permissions against   `protocol/infra`, which is bit tricky.

**Comment by lidel** [comment]
After discussing this today, and surprises in https://github.com/protocol/infra/pull/756  we decided to collapse complexity and go with simplified flow:

## Proposed design (B)

Make `dist.ipfs.io` DNSLink update work the same as  `webui.ipfs.io`: update it every time master changes.

1. Move `dist.ipfs.io` management from https://github.com/protocol/infra to dnssimple 
2. add DNSSIMPLE token to this repo
3. Update dnslink when master  is updated  (prior art: [ipfs-webui/.github/workflows/ci.yml#L133-L137](https://github.com/ipfs/ipfs-webui/blob/40a0ce536cb6a9c63b1fdb89f261b96e3fd391b8/.github/workflows/ci.yml#L133-L137))


@petar 1-2 will require help from infra, 3 can be added as the last step  in `persist` stage of [.github/workflows/main.yml](https://github.com/ipfs/distributions/blob/master/.github/workflows/main.yml#L98) in this repo

**Comment by thattommyhall** [comment]
Once the above PR is landed, you will be able to drive changes from here. 
We do intend to move from DNSimple to Cloudflare, so we'll need to migrate this with the other DNSimple ones but we can deal with that when we get to it

**Comment by BigLep** [comment]
For visibility, migration to Cloudflare for DNS is happening in https://github.com/protocol/infra/issues/754
