### ISSUE TITLE
make is failing on gobuilder

### ISSUE THREAD

**Issue by diasdavid** [ipfs/distributions#4]
```
» make all                                                                                               
echo "** making go-ipfs **"
** making go-ipfs **
cd dists/go-ipfs && make
chmod +x go-ipfs-dist
./go-ipfs-dist all
--> making v0.2.2
---> preparing ../../releases/go-ipfs/v0.2.2
---> getting archives from gobuilder...
No downloads has been found for your request.
---> failed.
error: failed to make v0.2.2
make[1]: *** [dist] Error 1
make: *** [go-ipfs] Error 2
```

**Comment by jbenet** [comment]
hey @Luzifer -- these are tags in go-ipfs:
- `v0.2.2` - https://github.com/ipfs/go-ipfs/tree/v0.2.2
- `v.0.2.3` - https://github.com/ipfs/go-ipfs/tree/v0.2.3

but they don't show up at all in https://gobuilder.me/github.com/ipfs/go-ipfs/cmd/ipfs -- these are old, so do we need to push them again, or something to trigger gobuilder building or something?

**Comment by Luzifer** [comment]
Just triggered them:

```
$ gobuilder-cli --repo=github.com/ipfs/go-ipfs@v0.2.2 build
Your build has been queued.
$ gobuilder-cli --repo=github.com/ipfs/go-ipfs@v0.2.3 build
Your build has been queued.
```

(This notation is also accepted by the web frontend)

Sadly those old tags are not buildable (anymore):

- `v0.2.2`: https://gobuilder.me/github.com/ipfs/go-ipfs/log/2a22d9ead6f3ec8d
- `v0.2.3`: https://gobuilder.me/github.com/ipfs/go-ipfs/log/8940c4113c635f7a

**Comment by jbenet** [comment]
@Luzifer ahhh, thank you!

**Comment by jbenet** [comment]
> Sadly those old tags are not buildable (anymore):
> 
> v0.2.2: https://gobuilder.me/github.com/ipfs/go-ipfs/log/2a22d9ead6f3ec8d
> v0.2.3: https://gobuilder.me/github.com/ipfs/go-ipfs/log/8940c4113c635f7a

:( this is why we _must vendor everything_. that's so annoying! :(
