### ISSUE TITLE
Cleanup build-info and build-log

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/distributions#44]
e.g. http://v04x.ipfs.io/ipfs/QmUA7DPsDZrp1qjDHfG9oGZM7Z1Jx7fosawHxu7B78rHz3/go-ipfs/v0.3.11/build-log

@whyrusleeping could you do this please?

**Comment by whyrusleeping** [comment]
i wanted both of those... those were on purpose

**Comment by jbenet** [comment]
@whyrusleeping see this issue: https://github.com/ipfs/distributions/issues/35

**Comment by Dignifiedquire** [comment]
Closing in favor of #35
