### ISSUE TITLE
Trying it out :) - Feedback

### ISSUE THREAD

**Issue by daviddias** [ipfs/distributions#45]
I've did a fresh `git clone`, `make all` and `gulp serve` to give a test to the new distributions page, before saying anything, huge ^5 for all the work put onto this! :)

Here are things I noticed:
- All the download links return 404.
  ![image](https://cloud.githubusercontent.com/assets/1211152/12494270/84bb175e-c089-11e5-9db4-a14e2a1463a0.png)
- I know you were following the ones in https://nodejs.org/en/download/, but since we don't have 'boxes', the lack of borders makes them look desaligned.
- Can we also have a link for the tarball with the source code?
- What is the plan to do with all the white space, for example in the go-ipfs? Will we add videos there?

**Comment by Dignifiedquire** [comment]
> All the download links return 404.

Yes the links will not work in development, if you want to test those run this:

```bash
$ npm i -g node-static
$ gulp build
$ static releases
```

This will build the site into the releases folder ready for a release, and with any static server you can now view it and test links.

**Comment by Dignifiedquire** [comment]
> Can we also have a link for the tarball with the source code?

Feels unnecessary to me, given that we link to the github repo where you can get this easily if you need to

**Comment by Dignifiedquire** [comment]
> I know you were following the ones in https://nodejs.org/en/download/, but since we don't have 'boxes', the lack of borders makes them look desaligned.

It's the eye of sauron :smiling_imp: 

![84bb175e-c089-11e5-9db4-a14e2a1463a0 copy](https://cloud.githubusercontent.com/assets/790842/12494616/8f4e8d98-c08b-11e5-871f-10b8b94c4e52.png)

**Comment by Dignifiedquire** [comment]
> What is the plan to do with all the white space, for example in the go-ipfs? Will we add videos there?

See user feedback for more details. In general it's important to have enough space between the individual "products" so that users can look at one at a time. But yes we plan to add more media in there, there is already an issue about adding asciinemas for go-ipfs.

**Comment by jbenet** [comment]
haha yes! or a tie fighter

**Comment by jbenet** [comment]
i think @diasdavid is right tho, we should align those vertically here i think.

**Comment by jbenet** [comment]
@Dignifiedquire +1 to the tarball source code, it makes things easier. some people want to build from source and do not want to have to install git in their deployment. or go hunt down links. this page is all about making things easier.

**Comment by Dignifiedquire** [comment]
We ca just link to the tarballs provided by github sure

**Comment by jessicaschilling** [comment]
Closing this issue - everything still outstanding is captured in other issues in this repo.
