### ISSUE TITLE
All release dates hardcoded to January 1, 2016

### ISSUE THREAD

**Issue by noffle** [ipfs/distributions#48]
see https://github.com/ipfs/distributions/blob/master/site/public/index.jade#L45

I'm guessing this was a workaround until release date got built into the build scripts. We can probably grab the date on the git tag that's being used.

**Comment by dignifiedquire** [comment]
Good point, wanna do a PR?

**Comment by jbenet** [comment]
:+1: on tag

**Comment by diasdavid** [comment]
They are good now :) (for a while)
