### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by harlantwood** [ipfs/distributions#49]
@dignifiedquire you mentioned in a hangout this week that making the JS builds reproducible is difficult. 

Wondering if this would help: https://github.com/webpack/webpack/issues/408
TL;DR add to webpack config plugins section: `new webpack.optimize.OccurenceOrderPlugin()`

I imagine doing `npm shrinkwrap` might help lock down dependencies as well.

You might be thinking of more sophisticated problems than I am though :wink:

**Comment by dignifiedquire** [comment]
@harlantwood those two would bring us most of the way probably. It might be fine with that, the one I'm afraid about is minification because I'm not a 100% sure that the renaming features and all that are reproducible, but we should give it a try.
