### ISSUE TITLE
Certificate issue?

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributions#521]
There seems to be an issue w/ the cert on https://dist.ipfs.io ?

```
> wget "https://dist.ipfs.io/ipfs-update/v1.7.1/ipfs-update_v1.7.1_linux-amd64.tar.gz"
--2021-12-15 12:52:54--  https://dist.ipfs.io/ipfs-update/v1.7.1/ipfs-update_v1.7.1_linux-amd64.tar.gz
Resolving dist.ipfs.io (dist.ipfs.io)... 2602:fea2:3::1, 209.94.78.1
Connecting to dist.ipfs.io (dist.ipfs.io)|2602:fea2:3::1|:443... connected.
ERROR: cannot verify dist.ipfs.io's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to dist.ipfs.io insecurely, use `--no-check-certificate'.
```

---

Found when: I got something similar downloading `go-ipfs` w/ `ipfs-update`
```
> ipfs-update install latest
ERROR: error resolving 'latest':  http.DefaultClient.Do error: Get https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/versions: x509: certificate has expired or is not yet valid
```

**Comment by aschmahmann** [comment]
I'm not seeing any issues from visiting the website, using ipfs-update, or `wget https://dist.ipfs.io/ipfs-update/v1.7.1/ipfs-update_v1.7.1_linux-amd64.tar.gz`. 

If you can give any more debugging information such as: running `curl -vI https://dist.ipfs.io/ipfs-update/v1.7.1/ipfs-update_v1.7.1_linux-amd64.tar.gz` and sharing the x-ipfs-gateway-host: header that would be great 🙏.

**Comment by jbenet** [comment]
Seems to have been a borked set of certificates (due to the Let's Encrypt root expiry). Manually removing and updating the cert fixed. 🤷
