### ISSUE TITLE
Replace go-ipfs v0.4.0-dev with v0.4.0-rc1

### ISSUE THREAD

**Issue by lgierth** [ipfs/distributions#54]
v0.4.0-dev is debris from when we tried to get gobuilder.me to build from the dev0.4.0 branch.

The only release of 0.4.0 so far is v0.4.0-rc1.

**Comment by dignifiedquire** [comment]
@whyrusleeping can you do this please?

**Comment by lgierth** [comment]
This has been resolved while releasing 0.4.0
