### ISSUE TITLE
Enforce two factor auth

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/distributions#55]
As this repository will play a crucial role in enabling code signing (Ref #51) we need to enforce 2fa for everyone who has write access to this repository:

- [x] @dignifiedquire
- [x] @diasdavid 
- [x] @jbenet 
- [x] @whyrusleeping 
- [x] @RichardLitt 
- [x] @lgierth

**Comment by diasdavid** [comment]
I've checked all that have checked https://github.com/ipfs/go-ipfs/issues/2227 as well (once you go 2FA for one repo, you go for all of them.

**Comment by dignifiedquire** [comment]
Cool, closing then :)
