### ISSUE TITLE
Invalid SSL cert

### ISSUE THREAD

**Issue by micxjo** [ipfs/distributions#59]
https://dist.ipfs.io is serving an SSL cert that doesn't match the subdomain. Since links have started appearing various places (e.g. the README at https://github.com/ipfs/go-ipfs) and the site currently prompts a giant insecure connection warning in most browsers, this should probably be addressed soon.

**Comment by Kubuxu** [comment]
I created PR to https://github.com/ipfs/go-ipfs/pull/2417 to remove usage of https://dist.ipfs.io/. It looks like cert with more subdomains isn't there yet.

**Comment by RichardLitt** [comment]
cc @lgierth

**Comment by micxjo** [comment]
Any update on this? https://ipfs.io/docs/install/ now has all the download links over HTTP, which isn't ideal.

**Comment by lgierth** [comment]
We're close -- getting the identity verification done was simply a massive PITA. Sorry about that, it's a matter of just a few more days.

**Comment by lgierth** [comment]
it's dohone!
