### ISSUE TITLE
`ipfs add -q -r releases` Doesn't work because electron app creates a symlink on the Libraries folder

### ISSUE THREAD

**Issue by diasdavid** [ipfs/distributions#6]
Following: https://github.com/ipfs/go-ipfs/issues/616#issuecomment-128964632

**Comment by Dignifiedquire** [comment]
Is this still relevant in the current version? @whyrusleeping @diasdavid

**Comment by diasdavid** [comment]
Nah, symlinks were fixed while ago, thank you for bringing this one up
