### ISSUE TITLE
Released artifacts must not change (prereq for 0.4.0 release)

### ISSUE THREAD

**Issue by lgierth** [ipfs/distributions#60]
I'm running `make` for the first time and it builds *everything*. Imagine if I was the one preparing a new release of something, this would change *all* artifacts of *everything*.

Instead, it should get all of dist.ipfs.io, and then only build what's missing, patch it in, and publish the result of that.

This is kind of urgent, since changed checksums of release artifacts will rightfully (and hopefully) set of alarm bells with users.

**Comment by dignifiedquire** [comment]
Are you sure checksums actually change? (except for 0.4 which is currently a moving target)

**Comment by Kubuxu** [comment]
Different go versions will for sure change the checksums because changes in stdlibs, optimizations and so on.

**Comment by lgierth** [comment]
> Are you sure checksums actually change? (except for 0.4 which is currently a moving target)

Are you sure they don't change? :P I'm pretty certain that neither the go dists nor the js dists build reproducibly.

**Comment by whyrusleeping** [comment]
okay, how about we make the build process take a list of tags (or general git refs) as an argument, and also as another argument, the root hash of an existing distributions release page to patch into.

**Comment by lgierth** [comment]
> okay, how about we make the build process take a list of tags (or general git refs) as an argument, and also as another argument, the root hash of an existing distributions release page to patch into.

That SGTM! The root hash can also be inferred from dist.ipfs.io by default or so.

**Comment by lgierth** [comment]
I think this was fixed in the process of releasing 0.4.0 as well
