### ISSUE TITLE
Include fonts rather than linking from CDN

### ISSUE THREAD

**Issue by lgierth** [ipfs/distributions#62]
#### ETA April 14, 2020
Visual standardization was fixed via https://github.com/ipfs/distributions/pull/289, but we still need to include the fonts used in the site so it can be fully delivered over IPFS.

#### ETA April 2020
Standardize CSS and fonts against those used in www.ipfs.io and/or docs-beta.ipfs.io to a degree that brings them visually into line with existing branded materials, but stopping short of effort-heavy rebranding (we'll be tackling this as part of overall approach to ipfs.io in the future).

#### Original issue text
It should ideally be vendored

**Comment by jbenet** [comment]
agreed it should

**Comment by diasdavid** [comment]
Fonts as well:

![image](https://user-images.githubusercontent.com/1211152/30309890-a32a04f0-9785-11e7-9a32-825a4d02849d.png)

**Comment by jessicaschilling** [comment]
CSS is now in line with overall IPFS look/feel, but let's use this issue to include the font files themselves; right now we're using Montserrat via Google's CDN.
