### ISSUE TITLE
enable google analytics website tracking 

### ISSUE THREAD

**Issue by dharmapunk82** [ipfs/distributions#621]
please add the following to the site header to enable google analytics tracking of the dist.ipfs.io site:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-96910779-9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-96910779-9');
</script>

**Comment by willscott** [comment]
Where is this request coming from?
It would be useful to have this linked to the underlying visibility desired, so that there's some context.

Adding this may require UX around cookie consent for GDPR, and there is currently fairly strong [pushback](https://tutanota.com/blog/posts/google-analytics/) against it's use.

**Comment by dharmapunk82** [comment]
Hi Will--

Apologies for nor providing more context.  There is no Foucaltian push to analytics everything, or anything like that.
 
I've been working to try and clean up our google analytics accounts.  I simply saw that there was an account for this site, no data flowing, and assumed (my mistake) that like a couple of other sites where tracking was lost inadvertently, the same was true here. 

If preferred, I can simply remove the google analytics tracking property, and note that we don't have analytics for the site (unless it's in countly or some other platform).

Feel free to close as a won't do or whatever is appropriate. 

Thanks!

Jeff

**Comment by lidel** [comment]
I vaguely remember we used Google Analytics before Countly, most likely we forgot to remove `dist.ipfs.io` from Google dashboard after switching to Countly in other places.

@dharmapunk82 if you can, please remove it from there, tracking users with JS from Google is not happening.
