### ISSUE TITLE
Builds of fs-repo-migrations for windows-amd64

### ISSUE THREAD

**Issue by lgierth** [ipfs/distributions#72]

**Comment by whyrusleeping** [comment]
There are builds for windows amd64 up? https://ipfs.io/ipfs/QmcKRDZ3LRSuuVhoKWonurQbrbFbtmaLswgSodEv1y4Mob/fs-repo-migrations/v1.1.0

**Comment by diasdavid** [comment]
![image](https://user-images.githubusercontent.com/1211152/30309956-03e10168-9786-11e7-9856-852bbc3c6268.png)
