### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by jbenet** [ipfs/distributions#8]
maybe we should have a small screenshot that shows what each "distribution" is
- the go-ipfs one could have a terminal with "ipfs add -r" mid-flight (with a progress bar, etc) 
- the electron app one could show the menubar menu + webui
- the webui dist (#7) could show the webui.

(let's start with pngs, and then levelup to short gifs.

**Comment by Dignifiedquire** [comment]
We will be using asciinemas and screenshots in the new design.
