### ISSUE TITLE
Generate "arm64" default download links for macOS on Apple Silicon

### ISSUE THREAD

**Issue by BigLep** [ipfs/distributions#840]
Currently the "download kubo" button at https://dist.ipfs.tech/#kubo when visited from an m1 Mac using an arm-based browser is 
https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_darwin-amd64.tar.gz
https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_darwin-arm64.tar.gz ← is what I would have expected.  (note "amd" to "arm")

Here is my browser:

<img width="707" alt="image" src="https://github.com/ipfs/distributions/assets/85411/988bc827-add0-4ec9-90a2-1ff180f2148c">

(Side: not directly related, but why do we denote intel-based macs as "amd" instead of "386" which is an option [here](https://github.com/ipfs/distributions/blob/581f5b1a29c1da6446f7e72e4b8860dc16d7b91d/site/assets/js/platform.js#LL5C49-L5C52))

**Comment by BigLep** [comment]
I'm assuming the issue is that the user agent is being reported as `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0`.  No mention of arm there.  

Detecting this looks to be a known open problem/challenge in JS: https://stackoverflow.com/questions/65146751/detecting-apple-silicon-mac-in-javascript

As a result, I'll close this as doesn't seem like possible to fix.  (Likely late to the party - learned something new.)

**Comment by lidel** [comment]
@BigLep my understanding is that all new Apple hardware is ARM, so maybe the real UX fix here is to switch to ARM by default?

Alternatively we could show both "Apple ARM" and "Intel" (so worst case user downloads invalid one, and then tries the second one).
